version: '2'

volumes:
  nerau_cx_crud_laravel-database:
    external: true

networks:
  nerau_cx_crud_laravel-network:
    external: true

services:
  nerau_cx_crud_laravel:
    image: ambientum/php:7.3-nginx
    container_name: nerau_cx_crud_laravel
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    networks:
      - nerau_cx_crud_laravel-network

  nerau_cx_crud_laravel-database:
    image: mysql:5.7
    volumes:
      - nerau_cx_crud_laravel-database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    networks:
      - nerau_cx_crud_laravel-network
